version: '3'

services:
  db:
    image: postgres
    env_file: .env
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
