# Generated by Django 4.0 on 2021-12-22 20:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('store', '0001_squashed_0004_alter_schedule_store'), ('store', '0002_store_comment'), ('store', '0003_alter_schedule_store_alter_store_comment'), ('store', '0004_alter_town_name_alter_street_unique_together'), ('store', '0005_alter_schedule_dayofweek')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='store.town')),
            ],
            options={
                'unique_together': {('Town', 'Name')},
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Number', models.CharField(max_length=10)),
                ('Street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='store.street')),
                ('Comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OpenTime', models.TimeField()),
                ('CloseTime', models.TimeField()),
                ('DayOfWeek', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)])),
                ('Store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Schedule', to='store.store')),
            ],
        ),
    ]
