# Generated by Django 4.0 on 2021-12-22 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='store.town')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Number', models.CharField(max_length=10)),
                ('Street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='store.town')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Begin', models.TimeField()),
                ('End', models.TimeField()),
                ('DayOfWeek', models.IntegerField()),
                ('Store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='store.store')),
            ],
        ),
    ]
