# Generated by Django 4.0 on 2021-12-22 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='End',
            new_name='CloseTime',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='Begin',
            new_name='OpenTime',
        ),
    ]
