# Generated by Django 4.0 on 2021-12-22 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='Store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Schedule', to='store.store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='Comment',
            field=models.TextField(blank=True),
        ),
    ]
