# Generated by Django 4.0 on 2021-12-22 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_store_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='Store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='store.store'),
        ),
    ]
